[colors.bright]
black = "#666666"
blue = "#7aa6da"
cyan = "#70c0b1"
green = "#30ff30"
magenta = "#d187c8"
red = "#f54e53"
white = "#efefef"
yellow = "#e7c547"

[colors.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#30ff30"
magenta = "#b294bb"
red = "#fc6666"
white = "#c5c8c6"
yellow = "#f0c674"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[window]
dynamic_title = true
opacity = 0.75
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0
