set runtimepath+=/home/aghriss/.config/vim,/home/aghriss/.config/vim/after
let g:python_host_prog = '/usr/bin/python'
let g:python3_host_prog = '/usr/bin/python'
py3 sys.path.append('/usr/lib/python3.11/site-packages')

" system clipboard
vmap <leader>y "*y
vmap <leader>p "*p
vmap <leader>P "*P

call plug#begin('/home/aghriss/.config/vim/plugged')

Plug 'preservim/nerdtree'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install' }
Plug 'lervag/vimtex'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'terryma/vim-multiple-cursors'
call plug#end()

" For deoplete plugin
let g:deoplete#enable_at_startup = 1
" This is new style
" call deoplete#custom#var('omni', 'input_patterns', {
"      \ 'tex': g:vimtex#re#deoplete
"      \})


" vimtex
let maplocalleader = ","
filetype plugin indent on
syntax enable
" set conceallevel=1
let g:vimtex_view_method = 'zathura'
" let g:tex_conceal='abdmg'
" let g:vimtex_view_general_viewer = 'zathura'
" let g:vimtex_view_general_options = 'zathura'




" Remap multiple-cursors shortcuts to match terryma/vim-multiple-cursors
" nmap <C-s> <Plug>NextWholeOccurrence
" xmap <C-s> <Plug>NextWholeOccurrence
" " nmap g<C-n> <Plug>NextOccurrence
" " xmap g<C-n> <Plug>NextOccurrence
" nmap <C-x> <Plug>SkipOccurrence
" xmap <C-x> <Plug>SkipOccurrence
" nmap <C-p> <Plug>RemoveOccurrence
" xmap <C-p> <Plug>RemoveOccurrence


" Default mapping
let g:multi_cursor_use_default_mapping = 0
let g:multi_cursor_start_word_key      = '<C-s>'
" let g:multi_cursor_select_all_word_key = '<A-n>'
" let g:multi_cursor_start_key           = 'g<C-n>'
" let g:multi_cursor_select_all_key      = 'g<A-n>'
let g:multi_cursor_next_key            = '<C-s>'
" let g:multi_cursor_prev_key            = '<C-p>'
let g:multi_cursor_skip_key            = '<C-x>'
let g:multi_cursor_quit_key            = '<Esc>'

" NERDTree
nmap <leader>t :NERDTreeToggle<cr>
nmap <leader>n :NERDTree<cr>
let NERDTreeMenuUp='e'
let NERDTreeMenuDown='n'
let NERDTreeMapOpenExpl='j'

" Colemak Up/down/left/right {{{
nnoremap m h|xnoremap m h|onoremap m h|
nnoremap n j|xnoremap n j|onoremap n j|
nnoremap e k|xnoremap e k|onoremap e k|
nnoremap i l|xnoremap i l|onoremap i l|
nnoremap h n|xnoremap h n|onoremap h n|
nnoremap l m|xnoremap l m|onoremap l m|
" }}}

" inSert/Replace/append (T) {{{
nnoremap t i|
nnoremap T I|
nnoremap z u|
" }}}

" next\last occurrence
    nnoremap ' n|
    nnoremap " N|
    
    
xnoremap p pgvy


" set surround
" set multiple-cursors
" set easymotion



function g:Multiple_cursors_before()
  call deoplete#custom#buffer_option('auto_complete', v:false)
endfunction
function g:Multiple_cursors_after()
  call deoplete#custom#buffer_option('auto_complete', v:true)
endfunction
