# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi


# Put your fun stuff here.
alias clean="sudo emerge -auv --depclean --changed-use"
alias lg="lazygit"
alias unmerge="sudo emerge -aC"
alias startvirt="virt-manager --connect qemu:///system"
alias todo="todo.sh"

function service(){
	if [[ $1 == "start" ]];	then
		echo Starting $2 service
		sudo rc-service $2 start
	elif [[ $1 == "stop" ]]; then
		echo Stopping $2 service
		sudo rc-service $2 stop
	elif [[ $1 == "restart" ]]; then
		echo Restarting $2 service
		sudo rc-service $2 restart
	else
		echo Undefined argument: $1
	fi
}

# alias list_all_mods="find /lib/modules/6.1.28-gentoo-framework11 -type f -name '*.ko*'"
# alias list_mods="cat /lib/modules/6.1.28-gentoo-framework11/modules.builtin"

trim() {
    local var="$*"
    # remove leading whitespace characters
    var="${var#"${var%%[![:space:]]*}"}"
    # remove trailing whitespace characters
    var="${var%"${var##*[![:space:]]}"}"
    printf '%s' "$var"
}

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# 
source ~/.config/zsh/manjaro-zsh-config
source ~/.config/zsh/manjaro-zsh-prompt
# header
# source ~/.config/zsh/headerc

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# source ~/.config/zsh/manjaro-p10k.zsh
source ~/.config/zsh/aghriss-p10k.zsh

source ~/.config/zsh/hashes.sh
export XMODIFIERS=@im=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus

# Use `xim` in case some Electron apps (like Chromium) refuse to work with IBus
# export GTK_IM_MODULE=xim
# export QT_IM_MODULE=xim

ibus-daemon -drx
